
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true # 초기 데이터 소스를 지연시킵니다

#  sql:
#    init:
#      mode: always
#      encoding: utf-8
#      schema-locations: classpath:/schema.sql
#      data-locations: classpath:/data.sql

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    net.devgrr.myfirstkotlin: debug

management:
  endpoints:
    web:
      #      base-path: /actuator
      #      path-mapping:
      #        health: health_check
      exposure:
        include: "*"
        exclude: "env,beans"